name: Build C++ Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up C++ Compiler
      run: sudo apt-get install -y g++

    - name: Compile all .cpp files
      run: |
        mkdir -p build
        g++ -std=c++17 -Wall -Wextra -o build/main *.cpp

    - name: Run the compiled binary
      run: ./build/main
